CREATE TABLE IF NOT EXISTS book (ISBN VARCHAR(18), name VARCHAR(128), author VARCHAR(128), price NUMERIC(12,2), publisher VARCHAR(128), number INT, PRIMARY KEY(ISBN)) ENGINE=MyISAM DEFAULT CHARSET=UTF8;
CREATE TABLE IF NOT EXISTS user (ID VARCHAR(18), name VARCHAR(128), telephone VARCHAR(14), password VARCHAR(128), PRIMARY KEY(ID)) ENGINE=MyISAM DEFAULT CHARSET=UTF8;
CREATE TABLE IF NOT EXISTS orders (OID int, ISBN VARCHAR(18), ID VARCHAR(18), count INT, PRIMARY KEY(OID), FOREIGN KEY (ISBN) REFERENCES book, FOREIGN KEY (ID) REFERENCES user) ENGINE=MyISAM DEFAULT CHARSET=UTF8;
